server:
  port: 0
spring:
  application:
    name: map-service
  datasource:
    url: jdbc:mysql://localhost:3306/AnimalWar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: User
      auto-offset-reset: earliest

      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka
        instance:
          instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
