
spring:
  application:
    name: map-service
  datasource:
    url: jdbc:mysql://localhost:3306/AnimalWar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: USER
      auto-offset-reset: earliest


server:
  port : 0